package domain;
// Generated 30-dic-2018 1:57:45 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Componentes generated by hbm2java
 */
public class Componentes implements java.io.Serializable {

	private Integer idComponent;
	private Usuario usuario;
	private String component;
	private String type;
	private double price;
	private String description;
	private Date registerDate;

	public Componentes() {
	}

	public Componentes(String component, String type, double price, String description, Date registerDate) {
		this.component = component;
		this.type = type;
		this.price = price;
		this.description = description;
		this.registerDate = registerDate;
	}

	public Componentes(Usuario usuario, String component, String type, double price, String description,
			Date registerDate) {
		this.usuario = usuario;
		this.component = component;
		this.type = type;
		this.price = price;
		this.description = description;
		this.registerDate = registerDate;
	}

	public Integer getIdComponent() {
		return this.idComponent;
	}

	public void setIdComponent(Integer idComponent) {
		this.idComponent = idComponent;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getComponent() {
		return this.component;
	}

	public void setComponent(String component) {
		this.component = component;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

}
