package domain;
// Generated 30-dic-2018 1:57:45 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Intercambios generated by hbm2java
 */
public class Intercambios implements java.io.Serializable {

	private Integer idChanges;
	private Componentes componentes;
	private Usuario usuarioByIdUserOwner;
	private Usuario usuarioByIdUserSeller;
	private double sellPrice;
	private Date sellDate;

	public Intercambios() {
	}

	public Intercambios(Componentes componentes, Usuario usuarioByIdUserOwner, Usuario usuarioByIdUserSeller,
			double sellPrice, Date sellDate) {
		this.componentes = componentes;
		this.usuarioByIdUserOwner = usuarioByIdUserOwner;
		this.usuarioByIdUserSeller = usuarioByIdUserSeller;
		this.sellPrice = sellPrice;
		this.sellDate = sellDate;
	}

	public Integer getIdChanges() {
		return this.idChanges;
	}

	public void setIdChanges(Integer idChanges) {
		this.idChanges = idChanges;
	}

	public Componentes getComponentes() {
		return this.componentes;
	}

	public void setComponentes(Componentes componentes) {
		this.componentes = componentes;
	}

	public Usuario getUsuarioByIdUserOwner() {
		return this.usuarioByIdUserOwner;
	}

	public void setUsuarioByIdUserOwner(Usuario usuarioByIdUserOwner) {
		this.usuarioByIdUserOwner = usuarioByIdUserOwner;
	}

	public Usuario getUsuarioByIdUserSeller() {
		return this.usuarioByIdUserSeller;
	}

	public void setUsuarioByIdUserSeller(Usuario usuarioByIdUserSeller) {
		this.usuarioByIdUserSeller = usuarioByIdUserSeller;
	}

	public double getSellPrice() {
		return this.sellPrice;
	}

	public void setSellPrice(double sellPrice) {
		this.sellPrice = sellPrice;
	}

	public Date getSellDate() {
		return this.sellDate;
	}

	public void setSellDate(Date sellDate) {
		this.sellDate = sellDate;
	}

}
